/**
 *
 * $Id$
 */
package qualitypatternmodel.textrepresentation.validation;

import qualitypatternmodel.parameters.Parameter;


/**
 * A sample validator interface for {@link qualitypatternmodel.textrepresentation.ParameterFragment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParameterFragmentValidator {
	boolean validate();

	boolean validateExampleValue(String value);

	boolean validateExampleValue(Parameter value);

}
