/**
 *
 * $Id$
 */
package qualitypatternmodel.operators.validation;

import qualitypatternmodel.graphstructure.ReturnType;
import qualitypatternmodel.parameters.ComparisonOptionParam;
import qualitypatternmodel.parameters.TypeOptionParam;

/**
 * A sample validator interface for {@link qualitypatternmodel.operators.Comparison}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComparisonValidator {
	boolean validate();

	boolean validateArgument1(qualitypatternmodel.graphstructure.Comparable value);

	boolean validateOption(ComparisonOptionParam value);
	boolean validateTypeOption(TypeOptionParam value);

	boolean validateArgument2(qualitypatternmodel.graphstructure.Comparable value);

	boolean validateType(ReturnType value);

}
