/**
 *
 * $Id$
 */
package qualitypatternmodel.operators.validation;

import org.eclipse.emf.common.util.EList;

import qualitypatternmodel.graphstructure.Graph;
import qualitypatternmodel.operators.Operator;

/**
 * A sample validator interface for {@link qualitypatternmodel.operators.OperatorList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperatorListValidator {
	boolean validate();

	boolean validateOperators(EList<Operator> value);
	boolean validateGraph(Graph value);
}
