/**
 *
 * $Id$
 */
package qualitypatternmodel.graphstructure.validation;

import org.eclipse.emf.common.util.EList;
import qualitypatternmodel.functions.Comparison;


/**
 * A sample validator interface for {@link qualitypatternmodel.graphstructure.GraphElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GraphElementValidator {
	boolean validate();

	boolean validateComparison1(EList<Comparison> value);

	boolean validateComparison2(EList<Comparison> value);

	boolean validateComparison(Comparison value);

}
