/**
 *
 * $Id$
 */
package qualitypatternmodel.graphstructure.validation;

import org.eclipse.emf.common.util.EList;
import qualitypatternmodel.functions.Match;
import qualitypatternmodel.functions.ReferenceOperator;
import qualitypatternmodel.graphstructure.Element;
import qualitypatternmodel.parameters.PropertyOption;
import qualitypatternmodel.parameters.Text;
import qualitypatternmodel.parameters.TextLiteral;

/**
 * A sample validator interface for {@link qualitypatternmodel.graphstructure.Property}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyValidator {
	boolean validate();

	boolean validatePropertyOption(PropertyOption value);
	boolean validateElement(Element value);
	boolean validateAttributeName(TextLiteral value);

	boolean validateOption(PropertyOption value);

	boolean validateReferenceOperator2(ReferenceOperator value);

	boolean validateReferenceOperator(ReferenceOperator value);

	boolean validateMatch(EList<Match> value);

	boolean validateAttributeName(Text value);
}
