/**
 *
 * $Id$
 */
package qualitypatternmodel.graphstructure.validation;

import org.eclipse.emf.common.util.EList;

import qualitypatternmodel.adaptionxml.XmlAxisKind;
import qualitypatternmodel.graphstructure.Node;
import qualitypatternmodel.graphstructure.Graph;
import qualitypatternmodel.patternstructure.RelationMapping;

/**
 * A sample validator interface for {@link qualitypatternmodel.graphstructure.Relation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationValidator {
	boolean validate();

	boolean validateIncomingMapping(RelationMapping value);

	boolean validateOutgoingMappings(EList<RelationMapping> value);

	boolean validateGraph(Graph value);

	boolean validateSource(Node value);

	boolean validateTarget(Node value);

	boolean validateName(String value);

	boolean validateMappingFrom(RelationMapping value);
	boolean validateMappingTo(EList<RelationMapping> value);

	boolean validateMappingTo(RelationMapping value);
	boolean validateAxis(XmlAxisKind value);
	boolean validateRelationTo(Node value);

	boolean validateGraphDepth(int value);
}
