/**
 *
 * $Id$
 */
package qualitypatternmodel.graphstructure.validation;

import org.eclipse.emf.common.util.EList;

import qualitypatternmodel.graphstructure.Element;
import qualitypatternmodel.graphstructure.SetElement;

/**
 * A sample validator interface for {@link qualitypatternmodel.graphstructure.SetElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SetElementValidator {
	boolean validate();

	boolean validateNext(EList<SetElement> value);
	boolean validatePrevious(Element value);

	boolean validateNestingDepth(int value);
}
