/**
 *
 * $Id$
 */
package qualitypatternmodel.graphstructure.validation;

import org.eclipse.emf.common.util.EList;

import qualitypatternmodel.graphstructure.Graph;
import qualitypatternmodel.graphstructure.SingleElement;

import qualitypatternmodel.patternstructure.SingleElementMapping;

/**
 * A sample validator interface for {@link qualitypatternmodel.graphstructure.SingleElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SingleElementValidator {
	boolean validate();

	boolean validateMappingTo(EList<SingleElementMapping> value);

	boolean validateMappingTo(SingleElementMapping value);
	boolean validateMappingFrom(SingleElementMapping value);
	boolean validatePrevious(SingleElement value);
	boolean validateNextSet(EList<SingleElement> value);

	boolean validateGraph(Graph value);

	boolean validateNext(EList<SingleElement> value);
	boolean validateRoot(Graph value);

	boolean validateNextSingle(EList<SingleElement> value);

	boolean validateGraphDepth(int value);
}
