/**
 */
package qualitypatternmodel.javaqueryoutput.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import qualitypatternmodel.javaqueryoutput.util.JavaqueryoutputAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class JavaqueryoutputItemProviderAdapterFactory extends JavaqueryoutputAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public JavaqueryoutputItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.javaqueryoutput.InterimResultStructure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterimResultStructureItemProvider interimResultStructureItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.javaqueryoutput.InterimResultStructure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterimResultStructureAdapter() {
		if (interimResultStructureItemProvider == null) {
			interimResultStructureItemProvider = new InterimResultStructureItemProvider(this);
		}

		return interimResultStructureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.javaqueryoutput.RecordInterim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RecordInterimItemProvider recordInterimItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.javaqueryoutput.RecordInterim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRecordInterimAdapter() {
		if (recordInterimItemProvider == null) {
			recordInterimItemProvider = new RecordInterimItemProvider(this);
		}

		return recordInterimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.javaqueryoutput.BooleanValueInterim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanValueInterimItemProvider booleanValueInterimItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.javaqueryoutput.BooleanValueInterim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanValueInterimAdapter() {
		if (booleanValueInterimItemProvider == null) {
			booleanValueInterimItemProvider = new BooleanValueInterimItemProvider(this);
		}

		return booleanValueInterimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.javaqueryoutput.ContainerInterim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerInterimItemProvider containerInterimItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.javaqueryoutput.ContainerInterim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerInterimAdapter() {
		if (containerInterimItemProvider == null) {
			containerInterimItemProvider = new ContainerInterimItemProvider(this);
		}

		return containerInterimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.javaqueryoutput.ValueListInterim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValueListInterimItemProvider valueListInterimItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.javaqueryoutput.ValueListInterim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValueListInterimAdapter() {
		if (valueListInterimItemProvider == null) {
			valueListInterimItemProvider = new ValueListInterimItemProvider(this);
		}

		return valueListInterimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.javaqueryoutput.NumberValueInterim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumberValueInterimItemProvider numberValueInterimItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.javaqueryoutput.NumberValueInterim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumberValueInterimAdapter() {
		if (numberValueInterimItemProvider == null) {
			numberValueInterimItemProvider = new NumberValueInterimItemProvider(this);
		}

		return numberValueInterimItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (interimResultStructureItemProvider != null) interimResultStructureItemProvider.dispose();
		if (recordInterimItemProvider != null) recordInterimItemProvider.dispose();
		if (booleanValueInterimItemProvider != null) booleanValueInterimItemProvider.dispose();
		if (containerInterimItemProvider != null) containerInterimItemProvider.dispose();
		if (valueListInterimItemProvider != null) valueListInterimItemProvider.dispose();
		if (numberValueInterimItemProvider != null) numberValueInterimItemProvider.dispose();
	}

}
