/**
 *
 * $Id$
 */
package qualitypatternmodel.execution.validation;

import org.eclipse.emf.common.util.EMap;

import qualitypatternmodel.execution.XmlSchemaDatabase;

/**
 * A sample validator interface for {@link qualitypatternmodel.execution.XmlDataDatabase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XmlDataDatabaseValidator {
	boolean validate();

	boolean validateRecordedAttributeValues(EMap<String, Integer> value);
	boolean validateRecordedDataValues(EMap<String, Integer> value);
	boolean validateXmlSchema(XmlSchemaDatabase value);
	boolean validateElementNames(EMap<String, Integer> value);
	boolean validateAttributeNames(EMap<String, Integer> value);
}
