/**
 *
 * $Id$
 */
package qualitypatternmodel.inputfields.validation;

import org.eclipse.emf.common.util.EList;

import qualitypatternmodel.graphstructure.Property;
import qualitypatternmodel.graphstructure.PropertyLocation;

/**
 * A sample validator interface for {@link qualitypatternmodel.inputfields.PropertyOption}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyOptionValidator {
	boolean validate();

	boolean validateOptions(EList<PropertyLocation> value);
	boolean validateValue(PropertyLocation value);

	boolean validateProperty(Property value);

	boolean validateSelection(PropertyLocation value);
}
