/**
 *
 * $Id$
 */
package qualitypatternmodel.inputfields.validation;

import org.eclipse.emf.common.util.EList;

import qualitypatternmodel.inputfields.Input;

import qualitypatternmodel.patternstructure.Pattern;

/**
 * A sample validator interface for {@link qualitypatternmodel.inputfields.VariableList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VariableListValidator {
	boolean validate();

	boolean validateVariables(EList<Input> value);
	boolean validatePattern(Pattern value);
}
