/**
 *
 * $Id$
 */
package qualitypatternmodel.patternstructure.validation;

import qualitypatternmodel.parameters.ComparisonOptionParam;

import qualitypatternmodel.patternstructure.CountConditionArgument;
import qualitypatternmodel.patternstructure.CountPattern;

/**
 * A sample validator interface for {@link qualitypatternmodel.patternstructure.CountCondition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CountConditionValidator {
	boolean validate();

	boolean validateCountPattern(CountPattern value);
	boolean validateOption(ComparisonOptionParam value);
	boolean validateArgument2(CountConditionArgument value);
}
