/**
 *
 * $Id$
 */
package qualitypatternmodel.patternstructure.validation;

import org.eclipse.emf.common.util.EList;

import qualitypatternmodel.graphstructure.Graph;

import qualitypatternmodel.patternstructure.Mapping;

/**
 * A sample validator interface for {@link qualitypatternmodel.patternstructure.Morphism}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MorphismValidator {
	boolean validate();

	boolean validateMappings(EList<Mapping> value);
	boolean validateFrom(Graph value);
	boolean validateTo(Graph value);

	boolean validateMorphDepth(int value);

	boolean validateCheckSingleElementMappings(Boolean value);

	boolean validateCheckRelationMappings(Boolean value);
}
