/**
 *
 * $Id$
 */
package qualitypatternmodel.patternstructure.validation;

import qualitypatternmodel.graphstructure.Graph;

import qualitypatternmodel.patternstructure.Condition;

/**
 * A sample validator interface for {@link qualitypatternmodel.patternstructure.Pattern}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PatternValidator {
	boolean validate();

	boolean validateGraph(Graph value);
	boolean validateCondition(Condition value);
	boolean validatePartialQuery(String value);
	boolean validateQuery(String value);
}
