/**
 *
 * $Id$
 */
package qualitypatternmodel.patternstructure.validation;

import qualitypatternmodel.graphstructure.Graph;

import qualitypatternmodel.patternstructure.Condition;
import qualitypatternmodel.patternstructure.Morphism;
import qualitypatternmodel.patternstructure.Quantifier;

/**
 * A sample validator interface for {@link qualitypatternmodel.patternstructure.QuantifiedCondition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface QuantifiedConditionValidator {
	boolean validate();

	boolean validateCondition(Condition value);
	boolean validateGraph(Graph value);
	boolean validateMorphism(Morphism value);
	boolean validateQuantifier(Quantifier value);

	boolean validateCheckMorphismOfNextGraph(boolean value);
}
