/**
 *
 * $Id$
 */
package qualitypatternmodel.patternstructure.validation;

import qualitypatternmodel.graphstructure.Relation;

/**
 * A sample validator interface for {@link qualitypatternmodel.patternstructure.RelationMapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationMappingValidator {
	boolean validate();

	boolean validateTarget(Relation value);

	boolean validateSource(Relation value);

	boolean validateTo(Relation value);
	boolean validateFrom(Relation value);
}
