<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qualitypatternmodel" nsURI="qualitypatternmodel" nsPrefix="qualitypatternmodel">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eSubpackages name="parameters" nsURI="parameters" nsPrefix="parameters">
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true" eSuperTypes="#//patternstructure/PatternElement">
      <eOperations name="inputIsValid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="generateDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
        <eParameters name="context">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="isUsed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getValueAsString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="setValueFromString" eExceptions="#//patternstructure/InvalidityExceptionWrapper">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getOptionsAsStringList" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" lowerBound="1"
          eType="#//parameters/ParameterList" eOpposite="#//parameters/ParameterList/parameters"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="predefined" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterFragments" upperBound="-1"
          eType="#//textrepresentation/ParameterFragment" eOpposite="#//textrepresentation/ParameterFragment/parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComparisonOptionParam" eSuperTypes="#//parameters/Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="options" upperBound="-1"
          eType="#//operators/ComparisonOperator"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="#//operators/ComparisonOperator"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="comparisons" upperBound="-1"
          eType="#//operators/Comparison" eOpposite="#//operators/Comparison/option"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="countConditions" upperBound="-1"
          eType="#//patternstructure/CountCondition" eOpposite="#//patternstructure/CountCondition/option"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyOptionParam" eSuperTypes="#//parameters/Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="options" upperBound="-1"
          eType="#//adaptionxml/PropertyKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="#//adaptionxml/PropertyKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//adaptionxml/XmlProperty" eOpposite="#//adaptionxml/XmlProperty/option"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterList" eSuperTypes="#//patternstructure/PatternElement">
      <eOperations name="add">
        <eParameters name="parameter" eType="#//parameters/Parameter"/>
      </eOperations>
      <eOperations name="remove">
        <eParameters name="parameter" eType="#//parameters/Parameter"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//parameters/Parameter" containment="true" eOpposite="#//parameters/Parameter/parameterList"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
          eType="#//patternstructure/CompletePattern" eOpposite="#//patternstructure/CompletePattern/parameterList"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanParam" eSuperTypes="#//parameters/ParameterValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="matches" upperBound="-1"
          eType="#//operators/Match" eOpposite="#//operators/Match/option"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextListParam" eSuperTypes="#//parameters/ParameterValue">
      <eOperations name="getListDeclaration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getListVar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextLiteralParam" eSuperTypes="#//parameters/ParameterValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="matches" upperBound="-1"
          eType="#//operators/Match" eOpposite="#//operators/Match/regularExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//adaptionxml/XmlProperty" eOpposite="#//adaptionxml/XmlProperty/attributeName"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberParam" eSuperTypes="#//parameters/ParameterValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
          defaultValueLiteral="0.0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="numberArgument" eType="#//patternstructure/NumberElement"
          eOpposite="#//patternstructure/NumberElement/numberParam"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterValue" abstract="true" eSuperTypes="#//parameters/Parameter #//graphstructure/Comparable">
      <eOperations name="isInTagComparison" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isInAttributeComparison" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isInDataComparison" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getTagComparisonElements" upperBound="-1" eType="#//adaptionxml/XmlElement"/>
      <eOperations name="inferElementTagSuggestions" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getElementTags">
        <eGenericType eClassifier="#//parameters/StringToIntEMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getAttributeNames">
        <eGenericType eClassifier="#//parameters/StringToIntEMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getDataValues">
        <eGenericType eClassifier="#//parameters/StringToIntEMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getAttributeValues">
        <eGenericType eClassifier="#//parameters/StringToIntEMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getSuggestions" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="replace">
        <eParameters name="concreteValue" eType="#//parameters/ParameterValue"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeModifiable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DateParam" eSuperTypes="#//parameters/ParameterValue">
      <eOperations name="specifyValue" eExceptions="#//patternstructure/InvalidityExceptionWrapper">
        <eParameters name="newValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeParam" eSuperTypes="#//parameters/ParameterValue">
      <eOperations name="specifyValue" eExceptions="#//patternstructure/InvalidityExceptionWrapper">
        <eParameters name="newValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UntypedParameterValue" eSuperTypes="#//parameters/ParameterValue">
      <eOperations name="setValue">
        <eParameters name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="replaceViaValue" eExceptions="#//patternstructure/InvalidityExceptionWrapper">
        <eParameters name="values" eType="#//parameters/StringArray"/>
        <eParameters name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DateTimeParam" eSuperTypes="#//parameters/ParameterValue">
      <eOperations name="specifyValue" eExceptions="#//patternstructure/InvalidityExceptionWrapper">
        <eParameters name="newValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RelationOptionParam" eSuperTypes="#//parameters/Parameter">
      <eOperations name="inferSuggestions" upperBound="-1" eType="#//adaptionxml/RelationKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="options" upperBound="-1"
          eType="#//adaptionxml/RelationKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="#//adaptionxml/RelationKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
          eType="#//adaptionxml/XmlNavigation" eOpposite="#//adaptionxml/XmlNavigation/option"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="StringToIntEMap" instanceClassName="org.eclipse.emf.common.util.EMap">
      <eTypeParameters name="K"/>
      <eTypeParameters name="V"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeOptionParam" eSuperTypes="#//parameters/Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="options" upperBound="-1"
          eType="#//graphstructure/ReturnType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="#//graphstructure/ReturnType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeComparisons" upperBound="-1"
          eType="#//operators/Comparison" eOpposite="#//operators/Comparison/typeOption"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="StringArray" instanceClassName="java.lang.String[]"/>
  </eSubpackages>
  <eSubpackages name="operators" nsURI="operators" nsPrefix="operators">
    <eClassifiers xsi:type="ecore:EClass" name="BooleanOperator" abstract="true" eSuperTypes="#//operators/Operator">
      <eOperations name="addElement">
        <eParameters name="element" eType="#//graphstructure/Element"/>
      </eOperations>
      <eOperations name="removeElement">
        <eParameters name="element" eType="#//graphstructure/Element"/>
      </eOperations>
      <eOperations name="createParameters"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//graphstructure/Element" eOpposite="#//graphstructure/Element/predicates"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operator" abstract="true" eSuperTypes="#//graphstructure/Comparable #//patternstructure/PatternElement">
      <eOperations name="getAllOperators" upperBound="-1" eType="#//operators/Operator"/>
      <eOperations name="getRootBooleanOperators" upperBound="-1" eType="#//operators/BooleanOperator"/>
      <eOperations name="isCycleFree" eExceptions="#//operators/OperatorCycleExceptionWrapper">
        <eParameters name="visitedOperators" upperBound="-1" eType="#//operators/Operator"/>
      </eOperations>
      <eOperations name="isCycleFree" eExceptions="#//operators/OperatorCycleExceptionWrapper"/>
      <eOperations name="getArguments" upperBound="-1" eType="#//graphstructure/Comparable"/>
      <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
        <eParameters name="context">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operatorList" lowerBound="1"
          eType="#//operators/OperatorList" eOpposite="#//operators/OperatorList/operators"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberOperator" abstract="true" eSuperTypes="#//operators/Operator"/>
    <eClassifiers xsi:type="ecore:EClass" name="Match" eSuperTypes="#//operators/BooleanOperator">
      <eOperations name="getElement" eType="#//graphstructure/Element"/>
      <eOperations name="copy" eType="#//operators/Match"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//graphstructure/Property"
          eOpposite="#//graphstructure/Property/match"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="option" lowerBound="1"
          eType="#//parameters/BooleanParam" eOpposite="#//parameters/BooleanParam/matches"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="regularExpression" lowerBound="1"
          eType="#//parameters/TextLiteralParam" eOpposite="#//parameters/TextLiteralParam/matches"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Comparison" eSuperTypes="#//operators/BooleanOperator">
      <eOperations name="isPrimitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getElement" eType="#//graphstructure/Element"/>
      <eOperations name="copy" eType="#//operators/Comparison"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="argument1" eType="#//graphstructure/Comparable"
          eOpposite="#//graphstructure/Comparable/comparison1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="argument2" eType="#//graphstructure/Comparable"
          eOpposite="#//graphstructure/Comparable/comparison2"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="option" lowerBound="1"
          eType="#//parameters/ComparisonOptionParam" eOpposite="#//parameters/ComparisonOptionParam/comparisons"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeOption" lowerBound="1"
          eType="#//parameters/TypeOptionParam" eOpposite="#//parameters/TypeOptionParam/typeComparisons"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ComparisonOperator">
      <eLiterals name="EQUAL" literal="="/>
      <eLiterals name="GREATER" value="1" literal=">"/>
      <eLiterals name="LESS" value="2" literal="&lt;"/>
      <eLiterals name="GREATEROREQUAL" value="3" literal=">="/>
      <eLiterals name="LESSOREQUAL" value="4" literal="&lt;="/>
      <eLiterals name="NOTEQUAL" value="5" literal="!="/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperatorList" eSuperTypes="#//patternstructure/PatternElement">
      <eOperations name="add">
        <eParameters name="Operator" eType="#//operators/Operator"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1"
          eType="#//graphstructure/Graph" eOpposite="#//graphstructure/Graph/operatorList"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operators" upperBound="-1"
          eType="#//operators/Operator" containment="true" eOpposite="#//operators/Operator/operatorList"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="OperatorCycleExceptionWrapper"
        instanceClassName="qualitypatternmodel.exceptions.OperatorCycleException"/>
  </eSubpackages>
  <eSubpackages name="graphstructure" nsURI="graphstructure" nsPrefix="graphstructure">
    <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="#//patternstructure/PatternElement #//graphstructure/Adaptable">
      <eOperations name="removeRelationFromPreviousGraphs"/>
      <eOperations name="removeMappingsToNext"/>
      <eOperations name="adaptAsXMLNavigation" eType="#//adaptionxml/XmlNavigation"/>
      <eOperations name="adaptAsXMLReference" eType="#//adaptionxml/XmlReference"/>
      <eOperations name="setGraphSimple">
        <eParameters name="newGraph" eType="#//graphstructure/Graph"/>
      </eOperations>
      <eOperations name="getOriginalID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingMapping" eType="#//patternstructure/RelationMapping"
          eOpposite="#//patternstructure/RelationMapping/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingMappings" upperBound="-1"
          eType="#//patternstructure/RelationMapping" eOpposite="#//patternstructure/RelationMapping/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1"
          eType="#//graphstructure/Graph" eOpposite="#//graphstructure/Graph/relations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//graphstructure/Element"
          eOpposite="#//graphstructure/Element/outgoing"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//graphstructure/Element"
          eOpposite="#//graphstructure/Element/incoming"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//graphstructure/Comparable #//patternstructure/PatternElement #//graphstructure/Adaptable">
      <eOperations name="copy" eType="#//graphstructure/Property"/>
      <eOperations name="addComparison" eType="#//operators/Comparison"/>
      <eOperations name="isOperatorArgument" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
          eType="#//graphstructure/Element" eOpposite="#//graphstructure/Element/properties"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="match" upperBound="-1"
          eType="#//operators/Match" eOpposite="#//operators/Match/property"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Element" eSuperTypes="#//graphstructure/Comparable #//patternstructure/PatternElement #//graphstructure/Adaptable">
      <eOperations name="getOriginalID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="addPrimitiveMatch">
        <eParameters name="regex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="addPrimitiveComparison">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="addPrimitiveMatch"/>
      <eOperations name="addPrimitiveComparison" eType="#//parameters/UntypedParameterValue"/>
      <eOperations name="getAllOperators" upperBound="-1" eType="#//operators/Operator"/>
      <eOperations name="addPrimitiveComparison">
        <eParameters name="operator" eType="#//operators/ComparisonOperator"/>
        <eParameters name="input" eType="#//parameters/ParameterValue"/>
      </eOperations>
      <eOperations name="addPrimitiveComparison">
        <eParameters name="input" eType="#//parameters/ParameterValue"/>
      </eOperations>
      <eOperations name="copyProperty" eType="#//graphstructure/Property">
        <eParameters name="property" eType="#//graphstructure/Property"/>
      </eOperations>
      <eOperations name="copyPrimitiveComparison" eExceptions="#//patternstructure/InvalidityExceptionWrapper">
        <eParameters name="comparison" eType="#//operators/Comparison"/>
      </eOperations>
      <eOperations name="copyMatch">
        <eParameters name="match" eType="#//operators/Match"/>
      </eOperations>
      <eOperations name="addNewProperty" eType="#//graphstructure/Property"/>
      <eOperations name="setGraphSimple">
        <eParameters name="newGraph" eType="#//graphstructure/Graph"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingMappings" upperBound="-1"
          eType="#//patternstructure/ElementMapping" eOpposite="#//patternstructure/ElementMapping/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingMapping" eType="#//patternstructure/ElementMapping"
          eOpposite="#//patternstructure/ElementMapping/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1"
          eType="#//graphstructure/Graph" eOpposite="#//graphstructure/Graph/elements"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultOf" eType="#//graphstructure/Graph"
          eOpposite="#//graphstructure/Graph/returnElements"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="translated" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="predicatesAreBeingTranslated"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//graphstructure/Property" containment="true" eOpposite="#//graphstructure/Property/element"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="predicates" upperBound="-1"
          eType="#//operators/BooleanOperator" eOpposite="#//operators/BooleanOperator/elements"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
          eType="#//graphstructure/Relation" eOpposite="#//graphstructure/Relation/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
          eType="#//graphstructure/Relation" eOpposite="#//graphstructure/Relation/target"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//patternstructure/PatternElement">
      <eOperations name="getAllOperators" upperBound="-1" eType="#//operators/Operator"/>
      <eOperations name="copyGraph" eExceptions="#//patternstructure/MissingPatternContainerException">
        <eParameters name="graph" eType="#//graphstructure/Graph"/>
      </eOperations>
      <eOperations name="isReturnGraph" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="addRelation" eType="#//graphstructure/Relation">
        <eParameters name="from" eType="#//graphstructure/Element"/>
        <eParameters name="to" eType="#//graphstructure/Element"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
          upperBound="-1" eType="#//graphstructure/Element" containment="true" eOpposite="#//graphstructure/Element/graph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operatorList" lowerBound="1"
          eType="#//operators/OperatorList" containment="true" eOpposite="#//operators/OperatorList/graph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="quantifiedCondition"
          eType="#//patternstructure/QuantifiedCondition" eOpposite="#//patternstructure/QuantifiedCondition/graph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//patternstructure/Pattern"
          eOpposite="#//patternstructure/Pattern/graph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnElements" lowerBound="1"
          upperBound="-1" eType="#//graphstructure/Element" eOpposite="#//graphstructure/Element/resultOf"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingMorphisms" upperBound="-1"
          eType="#//patternstructure/Morphism" eOpposite="#//patternstructure/Morphism/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingMorphism" eType="#//patternstructure/Morphism"
          eOpposite="#//patternstructure/Morphism/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
          eType="#//graphstructure/Relation" containment="true" eOpposite="#//graphstructure/Relation/graph"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Comparable" abstract="true" interface="true"
        eSuperTypes="#//patternstructure/PatternElement">
      <eOperations name="getReturnType" eType="#//graphstructure/ReturnType"/>
      <eOperations name="isTranslatable" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getAllArgumentElements" upperBound="-1" eType="#//graphstructure/Element"/>
      <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
        <eParameters name="context">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="comparison1" upperBound="-1"
          eType="#//operators/Comparison" eOpposite="#//operators/Comparison/argument1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="comparison2" upperBound="-1"
          eType="#//operators/Comparison" eOpposite="#//operators/Comparison/argument2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ReturnType">
      <eLiterals name="UNSPECIFIED" literal="UNSPECIFIED"/>
      <eLiterals name="STRING" value="1"/>
      <eLiterals name="BOOLEAN" value="2"/>
      <eLiterals name="ELEMENT" value="4"/>
      <eLiterals name="DATE" value="5" literal="DATE"/>
      <eLiterals name="TIME" value="6" literal="TIME"/>
      <eLiterals name="NUMBER" value="7" literal="NUMBER"/>
      <eLiterals name="DATETIME" value="8"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Adaptable" abstract="true" interface="true"
        eSuperTypes="#//patternstructure/PatternElement">
      <eOperations name="removeParametersFromParameterList"/>
      <eOperations name="createParameters"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="patternstructure" nsURI="patternstructure" nsPrefix="patternstructure">
    <eClassifiers xsi:type="ecore:EClass" name="RelationMapping" eSuperTypes="#//patternstructure/Mapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//graphstructure/Relation" eOpposite="#//graphstructure/Relation/incomingMapping"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//graphstructure/Relation" eOpposite="#//graphstructure/Relation/outgoingMappings"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QuantifiedCondition" eSuperTypes="#//patternstructure/Condition #//patternstructure/MorphismContainer">
      <eOperations name="checkMorphismOfNextGraph" eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantifier" eType="#//patternstructure/Quantifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1"
          eType="#//graphstructure/Graph" containment="true" eOpposite="#//graphstructure/Graph/quantifiedCondition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//patternstructure/Condition"
          containment="true" eOpposite="#//patternstructure/Condition/quantifiedCondition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true" eSuperTypes="#//patternstructure/PatternElement">
      <eOperations name="getNextMorphismContainers" upperBound="-1" eType="#//patternstructure/MorphismContainer"
          eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//patternstructure/Pattern"
          eOpposite="#//patternstructure/Pattern/condition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="quantifiedCondition"
          eType="#//patternstructure/QuantifiedCondition" eOpposite="#//patternstructure/QuantifiedCondition/condition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="formula1" eType="#//patternstructure/Formula"
          eOpposite="#//patternstructure/Formula/condition1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="formula2" eType="#//patternstructure/Formula"
          eOpposite="#//patternstructure/Formula/condition2"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="notCondition" eType="#//patternstructure/NotCondition"
          eOpposite="#//patternstructure/NotCondition/condition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Morphism" eSuperTypes="#//patternstructure/PatternElement">
      <eOperations name="checkElementMappings" eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eOperations name="checkRelationMappings" eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eOperations name="checkRelationMappingsUniqueness" eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eOperations name="checkElementMappingsUniqueness" eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eOperations name="addMapping" eType="#//patternstructure/ElementMapping">
        <eParameters name="from" eType="#//graphstructure/Element"/>
        <eParameters name="to" eType="#//graphstructure/Element"/>
      </eOperations>
      <eOperations name="addMapping" eType="#//patternstructure/RelationMapping">
        <eParameters name="from" eType="#//graphstructure/Relation"/>
        <eParameters name="to" eType="#//graphstructure/Relation"/>
      </eOperations>
      <eOperations name="removeInconsistentMappings"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
          eType="#//patternstructure/Mapping" containment="true" eOpposite="#//patternstructure/Mapping/morphism"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//graphstructure/Graph" eOpposite="#//graphstructure/Graph/outgoingMorphisms"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//graphstructure/Graph" eOpposite="#//graphstructure/Graph/incomingMorphism"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="morphismContainer" eType="#//patternstructure/MorphismContainer"
          eOpposite="#//patternstructure/MorphismContainer/morphism"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ElementMapping" eSuperTypes="#//patternstructure/Mapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//graphstructure/Element" eOpposite="#//graphstructure/Element/outgoingMappings"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//graphstructure/Element" eOpposite="#//graphstructure/Element/incomingMapping"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Mapping" abstract="true" eSuperTypes="#//patternstructure/PatternElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="morphism" lowerBound="1"
          eType="#//patternstructure/Morphism" eOpposite="#//patternstructure/Morphism/mappings"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Formula" eSuperTypes="#//patternstructure/Condition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//patternstructure/LogicalOperator"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition1" eType="#//patternstructure/Condition"
          containment="true" eOpposite="#//patternstructure/Condition/formula1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition2" eType="#//patternstructure/Condition"
          containment="true" eOpposite="#//patternstructure/Condition/formula2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TrueElement" eSuperTypes="#//patternstructure/Condition"/>
    <eClassifiers xsi:type="ecore:EEnum" name="LogicalOperator">
      <eLiterals name="AND" value="1" literal="and"/>
      <eLiterals name="OR" value="2" literal="or"/>
      <eLiterals name="IMPLIES" value="3" literal="implies"/>
      <eLiterals name="XOR" value="4" literal="xor"/>
      <eLiterals name="EQUAL" value="5" literal="equal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Quantifier">
      <eLiterals name="EXISTS" literal="EXISTS"/>
      <eLiterals name="FORALL" value="1" literal="FORALL"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompletePattern" eSuperTypes="#//patternstructure/Pattern">
      <eOperations name="getNewRefNo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eParameters name="type" eType="#//patternstructure/ClassWrapper"/>
      </eOperations>
      <eOperations name="recordValues" eExceptions="#//patternstructure/InvalidityExceptionWrapper #//operators/OperatorCycleExceptionWrapper #//patternstructure/MissingPatternContainerException"/>
      <eOperations name="getAbstractionLevel" eType="#//patternstructure/AbstractionLevel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" lowerBound="1"
          eType="#//parameters/ParameterList" containment="true" eOpposite="#//parameters/ParameterList/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="database" eType="#//execution/Database"
          eOpposite="#//execution/Database/patterns"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaptionStarted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaptionFinalized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementCounter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyCounter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationCounter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterCounter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorCounter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="counter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="text" upperBound="-1"
          eType="#//textrepresentation/PatternText" containment="true" eOpposite="#//textrepresentation/PatternText/pattern"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PatternElement" abstract="true">
      <eOperations name="generateQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eOperations name="getAllParameters" upperBound="-1" eType="#//parameters/Parameter"
          eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eOperations name="prepareTranslation"/>
      <eOperations name="isValid" eExceptions="#//patternstructure/InvalidityExceptionWrapper #//operators/OperatorCycleExceptionWrapper">
        <eParameters name="abstractionLevel" lowerBound="1" eType="#//patternstructure/AbstractionLevel"/>
      </eOperations>
      <eOperations name="isValidLocal" eExceptions="#//patternstructure/InvalidityExceptionWrapper #//operators/OperatorCycleExceptionWrapper">
        <eParameters name="abstractionLevel" lowerBound="1" eType="#//patternstructure/AbstractionLevel"/>
      </eOperations>
      <eOperations name="getContainer" eType="#//patternstructure/PatternElement"
          eExceptions="#//patternstructure/MissingPatternContainerException"/>
      <eOperations name="getAncestor" eType="#//patternstructure/PatternElement" eExceptions="#//patternstructure/MissingPatternContainerException">
        <eParameters name="cls" eType="#//patternstructure/ClassWrapper"/>
      </eOperations>
      <eOperations name="myToString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
        <eParameters name="context">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="prepareParameterUpdates" upperBound="-1" eType="#//patternstructure/PatternElement"/>
      <eOperations name="getParameterList" eType="#//parameters/ParameterList"/>
      <eOperations name="getOperatorList" eType="#//operators/OperatorList"/>
      <eOperations name="createXMLAdaption" eType="#//patternstructure/PatternElement"
          eExceptions="#//patternstructure/InvalidityExceptionWrapper #//operators/OperatorCycleExceptionWrapper #//patternstructure/MissingPatternContainerException"/>
      <eOperations name="finalizeXMLAdaption" eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eOperations name="recordValues">
        <eParameters name="database" eType="#//execution/XmlDataDatabase"/>
      </eOperations>
      <eOperations name="relationsXmlAdapted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="triggerParameterUpdates">
        <eParameters name="newContainer" eType="#//patternstructure/PatternElement"/>
        <eParameters name="patternElements" upperBound="-1" eType="#//patternstructure/PatternElement"/>
      </eOperations>
      <eOperations name="triggerParameterUpdates">
        <eParameters name="newContainer" eType="#//patternstructure/PatternElement"/>
      </eOperations>
      <eOperations name="updateParameters">
        <eParameters name="newParameterList" eType="#//parameters/ParameterList"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="internalId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="InvalidityExceptionWrapper" instanceClassName="qualitypatternmodel.exceptions.InvalidityException"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ClassWrapper" instanceClassName="java.lang.Class"/>
    <eClassifiers xsi:type="ecore:EDataType" name="MissingPatternContainerException"
        instanceClassName="qualitypatternmodel.exceptions.MissingPatternContainerException"/>
    <eClassifiers xsi:type="ecore:EClass" name="NotCondition" eSuperTypes="#//patternstructure/Condition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//patternstructure/Condition"
          containment="true" eOpposite="#//patternstructure/Condition/notCondition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CountCondition" eSuperTypes="#//patternstructure/Condition">
      <eOperations name="createParameters"/>
      <eOperations name="createCountPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="countPattern" lowerBound="1"
          eType="#//patternstructure/CountPattern" containment="true" eOpposite="#//patternstructure/CountPattern/countCondition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="option" lowerBound="1"
          eType="#//parameters/ComparisonOptionParam" eOpposite="#//parameters/ComparisonOptionParam/countConditions"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="argument2" eType="#//patternstructure/CountConditionArgument"
          containment="true" eOpposite="#//patternstructure/CountConditionArgument/countCondition2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CountConditionArgument" abstract="true"
        interface="true" eSuperTypes="#//patternstructure/PatternElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="countCondition2" eType="#//patternstructure/CountCondition"
          eOpposite="#//patternstructure/CountCondition/argument2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MorphismContainer" abstract="true"
        interface="true" eSuperTypes="#//patternstructure/PatternElement">
      <eOperations name="getGraph" eType="#//graphstructure/Graph"/>
      <eOperations name="copyPreviousGraph" eExceptions="#//patternstructure/MissingPatternContainerException"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="morphism" lowerBound="1"
          eType="#//patternstructure/Morphism" containment="true" eOpposite="#//patternstructure/Morphism/morphismContainer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CountPattern" eSuperTypes="#//patternstructure/Pattern #//patternstructure/MorphismContainer #//patternstructure/CountConditionArgument">
      <eStructuralFeatures xsi:type="ecore:EReference" name="countCondition" eType="#//patternstructure/CountCondition"
          eOpposite="#//patternstructure/CountCondition/countPattern"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern" abstract="true" eSuperTypes="#//patternstructure/PatternElement">
      <eOperations name="checkMorphismOfNextGraph" eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1"
          eType="#//graphstructure/Graph" containment="true" eOpposite="#//graphstructure/Graph/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//patternstructure/Condition"
          containment="true" eOpposite="#//patternstructure/Condition/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="partialQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberElement" eSuperTypes="#//patternstructure/CountConditionArgument">
      <eOperations name="createParameters"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="numberParam" lowerBound="1"
          eType="#//parameters/NumberParam" eOpposite="#//parameters/NumberParam/numberArgument"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AbstractionLevel">
      <eLiterals name="SEMI_GENERIC" literal="SEMI_GENERIC"/>
      <eLiterals name="GENERIC" value="1"/>
      <eLiterals name="SEMI_ABSTRACT" value="2"/>
      <eLiterals name="ABSTRACT" value="3"/>
      <eLiterals name="SEMI_CONCRETE" value="4"/>
      <eLiterals name="CONCRETE" value="5"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="adaptionxml" nsURI="adaptionxml" nsPrefix="adaptionxml">
    <eClassifiers xsi:type="ecore:EClass" name="XmlElement" eSuperTypes="#//graphstructure/Element">
      <eOperations name="getXQueryRepresentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eOperations name="getXQueryVariable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="translatePredicates" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eOperations name="getTagComparisons" upperBound="-1" eType="#//operators/Comparison"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XmlNavigation" eSuperTypes="#//graphstructure/Relation">
      <eOperations name="getOriginalOption" eType="#//parameters/RelationOptionParam"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="option" eType="#//parameters/RelationOptionParam"
          eOpposite="#//parameters/RelationOptionParam/relations"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XmlReference" eSuperTypes="#//graphstructure/Relation">
      <eOperations name="isTranslatable" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          eExceptions="#//patternstructure/InvalidityExceptionWrapper"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//graphstructure/ReturnType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetProperty" eType="#//adaptionxml/XmlProperty"
          eOpposite="#//adaptionxml/XmlProperty/incomingReferences"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceProperty" eType="#//adaptionxml/XmlProperty"
          eOpposite="#//adaptionxml/XmlProperty/outgoingReferences"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XmlProperty" eSuperTypes="#//graphstructure/Property">
      <eStructuralFeatures xsi:type="ecore:EReference" name="option" eType="#//parameters/PropertyOptionParam"
          eOpposite="#//parameters/PropertyOptionParam/properties"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeName" eType="#//parameters/TextLiteralParam"
          eOpposite="#//parameters/TextLiteralParam/properties"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingReferences" upperBound="-1"
          eType="#//adaptionxml/XmlReference" eOpposite="#//adaptionxml/XmlReference/targetProperty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingReferences" upperBound="-1"
          eType="#//adaptionxml/XmlReference" eOpposite="#//adaptionxml/XmlReference/sourceProperty"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PropertyKind">
      <eLiterals name="DATA" literal="DATA"/>
      <eLiterals name="TAG" value="1" literal="TAG"/>
      <eLiterals name="ATTRIBUTE" value="2" literal="ATTRIBUTE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="RelationKind">
      <eLiterals name="CHILD" literal="/child::*"/>
      <eLiterals name="DESCENDANT" value="1" literal="/descendant::*"/>
      <eLiterals name="PARENT" value="2" literal="/parent::*"/>
      <eLiterals name="ANCESTOR" value="3" literal="/ancestor::*"/>
      <eLiterals name="FOLLOWING" value="4" literal="/following::*"/>
      <eLiterals name="FOLLOWING_SIBLING" value="5" literal="/following-sibling::*"/>
      <eLiterals name="PRECEDING" value="6" literal="/preceding::*"/>
      <eLiterals name="PRECEDING_SIBLING" value="7" literal="/preceding-sibling::*"/>
      <eLiterals name="ANCESTOR_OR_SELF" value="8" literal="/ancestor-or-self::*"/>
      <eLiterals name="DESCENDANT_OR_SELF" value="9" literal="/descendant-or-self::*"/>
      <eLiterals name="SELF" value="10" literal="/self::*"/>
      <eLiterals name="TWOCHILD" value="11" literal="/*/*"/>
      <eLiterals name="THREECHILD" value="12" literal="/*/*/*"/>
      <eLiterals name="FOURCHILD" value="13" literal="/*/*/*/*"/>
      <eLiterals name="FIVECHILD" value="14" literal="/*/*/*/*/*"/>
      <eLiterals name="SIXCHILD" value="15" literal="/*/*/*/*/*/*"/>
      <eLiterals name="SEVENCHILD" value="16" literal="/*/*/*/*/*/*/*"/>
      <eLiterals name="EIGHTCHILD" value="17" literal="/*/*/*/*/*/*/*/*"/>
      <eLiterals name="NINECHILD" value="18" literal="/*/*/*/*/*/*/*/*/*"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XmlRoot" eSuperTypes="#//graphstructure/Element"/>
  </eSubpackages>
  <eSubpackages name="execution" nsURI="execution" nsPrefix="execution">
    <eClassifiers xsi:type="ecore:EClass" name="Result" abstract="true">
      <eOperations name="export">
        <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="database" eType="#//execution/Database"
          eOpposite="#//execution/Database/results"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="person" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="runtime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="problemNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
          eType="#//patternstructure/CompletePattern"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="splitResult" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XmlResult" eSuperTypes="#//execution/Result"/>
    <eClassifiers xsi:type="ecore:EClass" name="XmlDataDatabase" eSuperTypes="#//execution/XmlDatabase #//execution/Database">
      <eOperations name="recordAttributeValue">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="recordDataValue">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="removeAttributeValue">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="removeDataValue">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="recordElementName">
        <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="recordAttributeName">
        <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="removeElementName">
        <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="removeAttributeName">
        <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="addAttributeNames">
        <eParameters name="attributeNames" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="addElementNames">
        <eParameters name="elementNames" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="recordedAttributeValues"
          upperBound="-1" eType="#//execution/StringToIntMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="recordedDataValues" upperBound="-1"
          eType="#//execution/StringToIntMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="xmlSchema" eType="#//execution/XmlSchemaDatabase"
          eOpposite="#//execution/XmlSchemaDatabase/xmlDatabases"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementNames" upperBound="-1"
          eType="#//execution/StringToIntMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeNames" upperBound="-1"
          eType="#//execution/StringToIntMap" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LocalXmlDataDatabase" eSuperTypes="#//execution/XmlDataDatabase">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServerXmlDataDatabase" eSuperTypes="#//execution/XmlDataDatabase"/>
    <eClassifiers xsi:type="ecore:EClass" name="Databases">
      <eStructuralFeatures xsi:type="ecore:EReference" name="xmlDatabases" upperBound="-1"
          eType="#//execution/XmlDataDatabase" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="xmlSchemata" upperBound="-1"
          eType="#//execution/XmlSchemaDatabase" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="BaseXExceptionWrapper" instanceClassName="org.basex.core.BaseXException"/>
    <eClassifiers xsi:type="ecore:EDataType" name="QueryExceptionWrapper" instanceClassName="org.basex.query.QueryException"/>
    <eClassifiers xsi:type="ecore:EDataType" name="QueryIOExceptionWrapper" instanceClassName="org.basex.query.QueryIOException"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringToIntMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XmlSchemaDatabase" eSuperTypes="#//execution/XmlDatabase #//execution/Databaseformat">
      <eOperations name="checkFollowingInSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="elementName2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="checkParentInSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="elementName2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="checkAncestorInSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="elementName2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="checkPrecedingSiblingInSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="elementName2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="checkDescendantInSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="elementName2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="checkChildInSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="elementName2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="checkAttributeInSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="attributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="checkKeyRefInSchema" eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="elementName2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="checkPrecedingInSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="elementName2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="checkFollowingSiblingInSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="elementName2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getAncestorsInSchema" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getDescendantsInSchema" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getChildrenInSchema" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getFollowingInSchema" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getPrecedingInSchema" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getParentsInSchema" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getAttributesInSchema" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getFollowingSiblingsInSchema" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getPrecedingSiblingsInSchema" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="xmlDatabases" upperBound="-1"
          eType="#//execution/XmlDataDatabase" eOpposite="#//execution/XmlDataDatabase/xmlSchema"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementNames" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeNames" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rootElementNames" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LocalXmlSchemaDatabase" eSuperTypes="#//execution/XmlSchemaDatabase">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServerXmlSchemaDatabase" eSuperTypes="#//execution/XmlSchemaDatabase"/>
    <eClassifiers xsi:type="ecore:EClass" name="XmlDatabase" abstract="true">
      <eOperations name="analyse" eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper"/>
      <eOperations name="init" eExceptions="#//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper"/>
      <eOperations name="open" eExceptions="#//execution/BaseXExceptionWrapper"/>
      <eOperations name="create" eExceptions="#//execution/BaseXExceptionWrapper"/>
      <eOperations name="execute" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper #//execution/BaseXExceptionWrapper">
        <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Database" abstract="true" interface="true">
      <eOperations name="execute" eType="#//execution/Result" eExceptions="#//patternstructure/InvalidityExceptionWrapper #//operators/OperatorCycleExceptionWrapper #//patternstructure/MissingPatternContainerException #//execution/BaseXExceptionWrapper #//execution/QueryExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="pattern" eType="#//patternstructure/CompletePattern"/>
        <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="person" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="countMatches" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          eExceptions="#//execution/QueryExceptionWrapper #//patternstructure/InvalidityExceptionWrapper #//operators/OperatorCycleExceptionWrapper #//patternstructure/MissingPatternContainerException #//execution/BaseXExceptionWrapper #//execution/QueryIOExceptionWrapper">
        <eParameters name="pattern" eType="#//patternstructure/CompletePattern"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
          eType="#//execution/Result" containment="true" eOpposite="#//execution/Result/database"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" upperBound="-1"
          eType="#//patternstructure/CompletePattern" eOpposite="#//patternstructure/CompletePattern/database"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Databaseformat" abstract="true" interface="true"/>
  </eSubpackages>
  <eSubpackages name="textrepresentation" nsURI="textrepresentation" nsPrefix="textrepresentation">
    <eClassifiers xsi:type="ecore:EClass" name="PatternText">
      <eOperations name="generateJSON" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
          eType="#//patternstructure/CompletePattern" eOpposite="#//patternstructure/CompletePattern/text"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="textfragment" lowerBound="1"
          upperBound="-1" eType="#//textrepresentation/Fragment" containment="true"
          eOpposite="#//textrepresentation/Fragment/patternText"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterFragment" eSuperTypes="#//textrepresentation/Fragment">
      <eOperations name="getType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//parameters/Parameter" eOpposite="#//parameters/Parameter/parameterFragments"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fragment" abstract="true">
      <eOperations name="generateJSON" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="patternText" lowerBound="1"
          eType="#//textrepresentation/PatternText" eOpposite="#//textrepresentation/PatternText/textfragment"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextFragment" eSuperTypes="#//textrepresentation/Fragment">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ObjectWrapper" instanceClassName="java.lang.Object"/>
  </eSubpackages>
</ecore:EPackage>
