/**
 *
 * $Id$
 */
package qualitypatternmodel.functions.validation;

import org.eclipse.emf.common.util.EList;
import qualitypatternmodel.graphstructure.SingleElement;


/**
 * A sample validator interface for {@link qualitypatternmodel.functions.BooleanOperator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BooleanOperatorValidator {
	boolean validate();

	boolean validateElements(EList<SingleElement> value);

}
