/**
 *
 * $Id$
 */
package qualitypatternmodel.functions.validation;

import qualitypatternmodel.functions.ComparisonOperator;

import qualitypatternmodel.graphstructure.GraphElement;

import qualitypatternmodel.inputfields.Option;

/**
 * A sample validator interface for {@link qualitypatternmodel.functions.Comparison}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComparisonValidator {
	boolean validate();

	boolean validateArgument1(GraphElement value);
	boolean validateOption(Option<ComparisonOperator> value);
	boolean validateArgument2(GraphElement value);
}
