/**
 *
 * $Id$
 */
package qualitypatternmodel.parameters.validation;

import qualitypatternmodel.functions.Match;


/**
 * A sample validator interface for {@link qualitypatternmodel.parameters.Boolean}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BooleanValidator {
	boolean validate();

	boolean validateValue(Boolean value);

	boolean validateMatch(Match value);

	boolean validateBool(Boolean value);
}
