/**
 *
 * $Id$
 */
package qualitypatternmodel.parameters.validation;

import qualitypatternmodel.parameters.ParameterList;

/**
 * A sample validator interface for {@link qualitypatternmodel.parameters.Parameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParameterValidator {
	boolean validate();

	boolean validateVariableList(ParameterList value);
	boolean validateDescription(String value);
	boolean validateIsPredefined(boolean value);
}
