/**
 *
 * $Id$
 */
package qualitypatternmodel.parameters.validation;

import org.eclipse.emf.common.util.EList;

import qualitypatternmodel.graphstructure.ReturnType;

import qualitypatternmodel.operators.Comparison;

/**
 * A sample validator interface for {@link qualitypatternmodel.parameters.TypeOptionParam}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TypeOptionParamValidator {
	boolean validate();

	boolean validateOptions(EList<ReturnType> value);
	boolean validateValue(ReturnType value);
	boolean validateTypeComparisons(EList<Comparison> value);
}
