/**
 */
package qualitypatternmodel.execution.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import qualitypatternmodel.execution.util.ExecutionAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ExecutionItemProviderAdapterFactory extends ExecutionAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ExecutionItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.execution.XmlResult} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XmlResultItemProvider xmlResultItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.execution.XmlResult}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXmlResultAdapter() {
		if (xmlResultItemProvider == null) {
			xmlResultItemProvider = new XmlResultItemProvider(this);
		}

		return xmlResultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.execution.XmlDataDatabase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XmlDataDatabaseItemProvider xmlDataDatabaseItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.execution.XmlDataDatabase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXmlDataDatabaseAdapter() {
		if (xmlDataDatabaseItemProvider == null) {
			xmlDataDatabaseItemProvider = new XmlDataDatabaseItemProvider(this);
		}

		return xmlDataDatabaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.execution.LocalXmlDataDatabase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalXmlDataDatabaseItemProvider localXmlDataDatabaseItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.execution.LocalXmlDataDatabase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalXmlDataDatabaseAdapter() {
		if (localXmlDataDatabaseItemProvider == null) {
			localXmlDataDatabaseItemProvider = new LocalXmlDataDatabaseItemProvider(this);
		}

		return localXmlDataDatabaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.execution.ServerXmlDataDatabase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServerXmlDataDatabaseItemProvider serverXmlDataDatabaseItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.execution.ServerXmlDataDatabase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServerXmlDataDatabaseAdapter() {
		if (serverXmlDataDatabaseItemProvider == null) {
			serverXmlDataDatabaseItemProvider = new ServerXmlDataDatabaseItemProvider(this);
		}

		return serverXmlDataDatabaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.execution.Databases} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatabasesItemProvider databasesItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.execution.Databases}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatabasesAdapter() {
		if (databasesItemProvider == null) {
			databasesItemProvider = new DatabasesItemProvider(this);
		}

		return databasesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringToIntMapItemProvider stringToIntMapItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringToIntMapAdapter() {
		if (stringToIntMapItemProvider == null) {
			stringToIntMapItemProvider = new StringToIntMapItemProvider(this);
		}

		return stringToIntMapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.execution.XmlSchemaDatabase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XmlSchemaDatabaseItemProvider xmlSchemaDatabaseItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.execution.XmlSchemaDatabase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXmlSchemaDatabaseAdapter() {
		if (xmlSchemaDatabaseItemProvider == null) {
			xmlSchemaDatabaseItemProvider = new XmlSchemaDatabaseItemProvider(this);
		}

		return xmlSchemaDatabaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.execution.LocalXmlSchemaDatabase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalXmlSchemaDatabaseItemProvider localXmlSchemaDatabaseItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.execution.LocalXmlSchemaDatabase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalXmlSchemaDatabaseAdapter() {
		if (localXmlSchemaDatabaseItemProvider == null) {
			localXmlSchemaDatabaseItemProvider = new LocalXmlSchemaDatabaseItemProvider(this);
		}

		return localXmlSchemaDatabaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.execution.ServerXmlSchemaDatabase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServerXmlSchemaDatabaseItemProvider serverXmlSchemaDatabaseItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.execution.ServerXmlSchemaDatabase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServerXmlSchemaDatabaseAdapter() {
		if (serverXmlSchemaDatabaseItemProvider == null) {
			serverXmlSchemaDatabaseItemProvider = new ServerXmlSchemaDatabaseItemProvider(this);
		}

		return serverXmlSchemaDatabaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link qualitypatternmodel.execution.BaseXClient} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BaseXClientItemProvider baseXClientItemProvider;

	/**
	 * This creates an adapter for a {@link qualitypatternmodel.execution.BaseXClient}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBaseXClientAdapter() {
		if (baseXClientItemProvider == null) {
			baseXClientItemProvider = new BaseXClientItemProvider(this);
		}

		return baseXClientItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (xmlResultItemProvider != null) xmlResultItemProvider.dispose();
		if (xmlDataDatabaseItemProvider != null) xmlDataDatabaseItemProvider.dispose();
		if (localXmlDataDatabaseItemProvider != null) localXmlDataDatabaseItemProvider.dispose();
		if (serverXmlDataDatabaseItemProvider != null) serverXmlDataDatabaseItemProvider.dispose();
		if (databasesItemProvider != null) databasesItemProvider.dispose();
		if (stringToIntMapItemProvider != null) stringToIntMapItemProvider.dispose();
		if (xmlSchemaDatabaseItemProvider != null) xmlSchemaDatabaseItemProvider.dispose();
		if (localXmlSchemaDatabaseItemProvider != null) localXmlSchemaDatabaseItemProvider.dispose();
		if (serverXmlSchemaDatabaseItemProvider != null) serverXmlSchemaDatabaseItemProvider.dispose();
		if (baseXClientItemProvider != null) baseXClientItemProvider.dispose();
	}

}
