/**
 *
 * $Id$
 */
package qualitypatternmodel.adaptionxml.validation;

import org.eclipse.emf.common.util.EList;

import qualitypatternmodel.adaptionxml.PropertyKind;
import qualitypatternmodel.adaptionxml.XmlProperty;
import qualitypatternmodel.graphstructure.PrimitiveNode;

/**
 * A sample validator interface for {@link qualitypatternmodel.adaptionxml.PropertyOptionParam}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyOptionParamValidator {
	boolean validate();

	boolean validateOptions(EList<PropertyKind> value);
	boolean validateValue(PropertyKind value);

	boolean validateProperties(EList<XmlProperty> value);

	boolean validateProperty(PrimitiveNode value);

	boolean validateSelection(PropertyKind value);
}
