/**
 *
 * $Id$
 */
package qualitypatternmodel.adaptionxml.validation;

import org.eclipse.emf.common.util.EList;

import qualitypatternmodel.adaptionxml.PropertyOptionParam;
import qualitypatternmodel.adaptionxml.XmlReference;
import qualitypatternmodel.parameters.TextLiteralParam;

/**
 * A sample validator interface for {@link qualitypatternmodel.adaptionxml.XmlProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XmlPropertyValidator {
	boolean validate();

	boolean validateOption(PropertyOptionParam value);
	boolean validateAttributeName(TextLiteralParam value);
	boolean validateIncomingReferences(EList<XmlReference> value);
	boolean validateOutgoingReferences(EList<XmlReference> value);
}
