name: BuildAndPushDockerImageToHarbor

on:
  push:
    branches: [ "master", "development2" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for tags
          
      - name: Harbor Login
        uses: docker/login-action@v3
        with:
          registry: harbor.gwdg.de
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Get Maven Project Version
        run: |
          cd qualitypatternmodel
          POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          BASE_VERSION=${POM_VERSION%.0}
          MASTER_PATCH=$(git rev-list v$POM_VERSION..origin/master --count --first-parent)
          BASE_COMMIT=$(git merge-base origin/master HEAD)
          DEV_PATCH=$(git rev-list $BASE_COMMIT..HEAD --count)
          MASTER_VERSION="$BASE_VERSION.$MASTER_PATCH"
          DEV_VERSION="dev-$BASE_VERSION.$MASTER_PATCH.$DEV_PATCH"
          echo "DEV_PATCH=$DEV_PATCH" >> "$GITHUB_ENV"
          echo "DEV_VERSION=$DEV_VERSION" >> "$GITHUB_ENV"
          echo "MAIN_VERSION=$MASTER_VERSION" >> "$GITHUB_ENV"

      - name: Harbor Build and Push (master)
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name == 'master'  && env.DEV_PATCH == '0' }}
        with:
          context: qualitypatternmodel
          file: qualitypatternmodel/Dockerfile
          build-args: MAVEN_VERSION=${{ env.MAIN_VERSION }}
          push: true
          tags: harbor.gwdg.de/aqinda/qpm:latest, harbor.gwdg.de/aqinda/qpm:${{ env.MAIN_VERSION }}, harbor.gwdg.de/aqinda/qpm:${{ env.DEV_VERSION }}, harbor.gwdg.de/aqinda/qpm:current

      - name: Harbor Build and Push (development2)
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name == 'development2' && env.DEV_PATCH != '0' }}
        with:
          context: qualitypatternmodel
          file: qualitypatternmodel/Dockerfile
          build-args: MAVEN_VERSION=${{ env.DEV_VERSION }}
          push: true
          tags: harbor.gwdg.de/aqinda/qpm:dev, harbor.gwdg.de/aqinda/qpm:${{ env.DEV_VERSION }}, harbor.gwdg.de/aqinda/qpm:current
