name: BuildAndPushDockerImageToHarbor

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for tags
          
      - name: Harbor Login
        uses: docker/login-action@v3
        with:
          registry: harbor.gwdg.de
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Get Maven Project Version
        if: ${{ github.ref_name == 'main' || github.ref_name == 'develop' }}
        run: |
          cd qualitypatternmodel
          POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          BASE_VERSION=${POM_VERSION%.0}
          MAIN_PATCH=$(git rev-list v$POM_VERSION..origin/main --count --first-parent)
          BASE_COMMIT=$(git merge-base origin/main HEAD)
          DEV_PATCH=$(git rev-list --first-parent $BASE_COMMIT..HEAD --count)
          MAIN_VERSION="$BASE_VERSION.$MAIN_PATCH"
          DEV_VERSION="dev-$BASE_VERSION.$MAIN_PATCH.$DEV_PATCH"
          echo "DEV_PATCH=$DEV_PATCH" >> "$GITHUB_ENV"
          echo "DEV_VERSION=$DEV_VERSION" >> "$GITHUB_ENV"
          echo "MAIN_VERSION=$MAIN_VERSION" >> "$GITHUB_ENV"

      - name: Harbor Build and Push (main)
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name == 'main'  && env.DEV_PATCH == '0' }}
        with:
          context: qualitypatternmodel
          file: qualitypatternmodel/Dockerfile
          build-args: MAVEN_VERSION=${{ env.MAIN_VERSION }}
          push: true
          tags: harbor.gwdg.de/aqinda/qpm:latest, harbor.gwdg.de/aqinda/qpm:${{ env.MAIN_VERSION }}, harbor.gwdg.de/aqinda/qpm:${{ env.DEV_VERSION }}, harbor.gwdg.de/aqinda/qpm:current

      - name: Harbor Build and Push (develop)
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name == 'develop' && env.DEV_PATCH != '0' }}
        with:
          context: qualitypatternmodel
          file: qualitypatternmodel/Dockerfile
          build-args: MAVEN_VERSION=${{ env.DEV_VERSION }}
          push: true
          tags: harbor.gwdg.de/aqinda/qpm:dev, harbor.gwdg.de/aqinda/qpm:${{ env.DEV_VERSION }}, harbor.gwdg.de/aqinda/qpm:current

      - name: Harbor Build and Push (other branch)
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name != 'main'  && github.ref_name != 'develop' }}
        with:
          context: qualitypatternmodel
          file: qualitypatternmodel/Dockerfile
          build-args: MAVEN_VERSION=SNAPSHOT
          push: true
          tags: harbor.gwdg.de/aqinda/qpm:SNAPSHOT, harbor.gwdg.de/aqinda/qpm:current
